### ISSUE TITLE
Confusion about GT normal map preprocessing in NAS

### ISSUE THREAD

**Issue by XiWJ** [udaykusupati/Normal-Assisted-Stereo#2]
Sorry to bother you again. I have some confusions about ground truth normal preprocessing in the [data_loader.py](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/master/data_loader.py) of NAS. And I look forward to your help!

In the lines from [336 to 338](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/6bb596c18d66b4dc132c54560293cfc50c235ba9/data_loader.py#L336) of [data_loader.py](https://github.com/udaykusupati/Normal-Assisted-Stereo/blob/master/data_loader.py) are the part of load the gt normal map and preprocessing. The `sample['gt_nmap']` is range from 0 to 1, not **from -1 to 1**. And through the line 337 and 338, the `gt_nmap[:, :, :2]` are range from -1 to 1, but the `gt_nmap[:, :, 2]` is range **from -1 to 0**.

This means that the $n = (n_x, n_y, n_z)$, the ranges of $n_x, n_y$ are (-1, 1), and the range of $n_z$ is (-1, 0]. Could you tell me why you did this processing? And could you give me some suggestion on how to process these gt_nmaps to the real-world normal which range from -1 to 1? If you can show me the code of process gt_nmap to real-world normal and draw, I will thank you sincerely!

I look forward to your help!

**Comment by udaykusupati** [comment]
Though the range of $n_z$ is theoretically [-1,1], I change it to [-1,0] because if you look at the values almost all of the $n_z$ will be in [-1,0], this is because, for a normal map, every pixel has a normal with a negative z component by definition(you can't take the image of a back surface), so any positive values are outliers/errors, so I just make them negative. 

I don't completely understand what you mean by real-world normal. Normalizing the gt_nmap input would be the normal vectors for each pixel and you can visualize it as shown in the paper by casting 255*(-nmap + 1)/2 to np.uint8 and saving it as a png.

**Comment by XiWJ** [comment]
Many thanks! Your suggestion is very important to me.
